---

- name: Generate an OpenSSH keypair to work with ansible
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa

- name: Provisioning cluster (3 nodes as "real" servers)
  docker_container:
    name: "{{ 'h%d'|format(item) }}"
    image: afefelov/baseimage-dind
    privileged: true
    env:
      TERM: 'xterm'
      TZ: Europe/Moscow
    volumes:
      - /root/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    expose:
      - 22
      - 8301
      - "8301/udp"
      - 8300
      - 8500
      - 5432
      - 8008
  loop: "{{ range(0, 3)| list }}"
